name: package

on: push
env:
  IMAGE_NAME: edjtest

jobs:
  # Build and run tests.
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Kubernetes cluster
    - uses: Azure/k8s-deploy@v1.1.0
      with:
        images:  hello-world


