name: package

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Kubernetes cluster
    - uses: Azure/k8s-deploy@v1.1.0
      with:
        images:  hello-world


